In [1]:
import h5py

In [2]:
raw_db = h5py.File("e:\\Books\\Data\\20220825_L2Tick.h5", "r")

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'e:\Books\Data\20220825_L2Tick.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [14]:
for i, name in enumerate(raw_db):
    print(name)

SH.510050
SH.510300

In [1]:
import os
path = os.path.abspath("../quantself/")
print(path)

d:\Books\quantself

In [ ]:
from configs import project_path

In [9]:
db_path = os.path.join(project_path, "Data")

'e:\\Books\\Data'

In [3]:
import pandas as pd

In [10]:
df = pd.read_hdf("e:\\Books\\Books\\Data\\20220825_L2Tran.h5", "SH.510050")

In [11]:
df.iloc[5000:5030]

,ActionDate,SeqNo,Channel,ExTime,Price,Volume,Turnover,BidNo,AskNo,BSFlag
5000,20220825,618786,4,94827360,27610,80000,220880,1102545,1112555,83
5001,20220825,619292,4,94828440,27620,600,1657,1113304,754810,66
5002,20220825,619361,4,94828670,27620,6000,16572,1113465,754810,66
5003,20220825,619484,4,94829130,27620,1100,3038,1113761,754810,66
5004,20220825,620053,4,94830260,27620,5000,13810,1114437,754810,66
5005,20220825,620497,4,94831360,27610,300000,828300,1102545,1115147,83
5006,20220825,620700,4,94831860,27610,100000,276100,1102545,1115497,83
5007,20220825,620733,4,94831910,27610,10000,27610,1102545,1115566,83
5008,20220825,620939,4,94832480,27610,90400,249594,1102545,1116064,83
5009,20220825,621037,4,94832800,27610,2000,5522,1102545,1116235,83
5010,20220825,621348,4,94833810,27610,18000,49698,1104117,1116859,83
5011,20220825,621349,4,94833810,27610,282000,778602,1105720,1116859,83
5012,20220825,621649,4,94834390,27620,300,829,1117267,754810,66
5013,20220825,621749,4,94834560,27610,18000,49698,1105720,1117350,83
5014,20220825,621750,4,94834560,27610,28800,79517,1108347,1117350,83
5015,20220825,621774,4,94834660,27610,11200,30923,1108347,1117412,83
5016,20220825,621775,4,94834660,27610,500,1381,1117128,1117412,83
5017,20220825,621935,4,94834990,27610,1000,2761,1117618,1117412,66
5018,20220825,622138,4,94835590,27610,100,276,1117965,1117412,66
5019,20220825,622942,4,94838320,27610,37200,102709,1119621,1117412,66
5020,20220825,622943,4,94838320,27610,4000,11044,1119621,1119404,66
5021,20220825,623006,4,94838470,27610,3500,9664,1119621,1119686,83
5022,20220825,623112,4,94838750,27610,2000,5522,1119621,1119824,83
5023,20220825,623115,4,94838770,27610,2000,5522,1119621,1119832,83
5024,20220825,623317,4,94839300,27610,4000,11044,1120066,1120141,83
5025,20220825,623440,4,94839480,27620,800,2210,1120247,754810,66
5026,20220825,623501,4,94839890,27610,5000,13805,1120066,1120427,83
5027,20220825,623502,4,94839890,27610,500,1381,1120254,1120427,83
5028,20220825,623529,4,94839960,27610,3000,8283,1120254,1120474,83
5029,20220825,623819,4,94840420,27610,10000,27610,1120254,1120861,83

In [25]:
raw_db_data.to_parquet("e:\\Books\\Data\\510050.SH.parquet")

In [26]:
data = pd.read_parquet("e:\\Books\\Data\\510050.SH.parquet")

In [27]:
data

,TradeDate,ExTime,Status,PreClosePx,OpenPx,HighPx,LowPx,LastPx,OfferPx_0,OfferPx_1,...,IOPV,Ytm,HighLimitPx,LowLimitPx,SecPrefix,Syl1,Syl2,SD2,TradingPhaseCode,PreIOPV
0,20220825,85648000,69,27460,0,0,0,0,0,0,...,0,0,30210,24710,,0,0,0,S 10,0
1,20220825,90048000,69,27460,0,0,0,0,0,0,...,0,0,30210,24710,,0,0,0,S 10,0
2,20220825,91148000,69,27460,0,0,0,0,0,0,...,0,0,30210,24710,,0,0,0,S 10,0
3,20220825,91400000,73,27460,0,0,0,0,0,0,...,0,0,30210,24710,,0,0,0,S 10,0
4,20220825,91430000,73,27460,0,0,0,0,0,0,...,27480,0,30210,24710,,0,0,0,C111,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,20220825,152811000,86,27460,27530,27990,27470,27930,27940,27950,...,27920,0,30210,24710,,0,0,0,E110,0
4962,20220825,153110000,86,27460,27530,27990,27470,27930,27940,27950,...,27920,0,30210,24710,,0,0,0,E110,0
4963,20220825,153410000,86,27460,27530,27990,27470,27930,27940,27950,...,27920,0,30210,24710,,0,0,0,E110,0
4964,20220825,153611000,86,27460,27530,27990,27470,27930,27940,27950,...,27920,0,30210,24710,,0,0,0,E110,0
4965,20220825,153911000,86,27460,27530,27990,27470,27930,27940,27950,...,27920,0,30210,24710,,0,0,0,E110,0